/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Systemc19_telas;

import Systemc19_classes.GerenciadorDeData;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author jhoni
 */
public class TelaGerarRelatorios extends javax.swing.JInternalFrame {

    DateFormat format = new SimpleDateFormat("dd-MM-yyyy");
    
    public TelaGerarRelatorios() {
        initComponents();
        mudarLingCalen();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        textoData = new javax.swing.JLabel();
        textoDestaque = new javax.swing.JLabel();
        textoIdadeA = new javax.swing.JLabel();
        textoIdadeB = new javax.swing.JLabel();
        textoIdadeC = new javax.swing.JLabel();
        textoIdadeD = new javax.swing.JLabel();
        textoResA = new javax.swing.JLabel();
        textoResB = new javax.swing.JLabel();
        textoResC = new javax.swing.JLabel();
        textoResD = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        botaoCalcular = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        campoDataInicial = new com.toedter.calendar.JDateChooser();
        campoDataFinal = new com.toedter.calendar.JDateChooser();

        jButton5.setBackground(new java.awt.Color(85, 78, 164));
        jButton5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("MÉDIA");
        jButton5.setBorder(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(85, 78, 164));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(85, 78, 164));
        jLabel2.setText("GERAR RELATÓRIOS");

        textoData.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        textoData.setForeground(new java.awt.Color(0, 0, 0));
        textoData.setText("Data Incial/Final:");

        textoDestaque.setBackground(new java.awt.Color(85, 78, 164));
        textoDestaque.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textoDestaque.setForeground(new java.awt.Color(85, 78, 164));
        textoDestaque.setText("Media Vacinações");

        textoIdadeA.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        textoIdadeA.setForeground(new java.awt.Color(0, 0, 0));
        textoIdadeA.setText("Idade maior ou igual á 90 :");

        textoIdadeB.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        textoIdadeB.setForeground(new java.awt.Color(0, 0, 0));
        textoIdadeB.setText("Idade 70 á 89 :");

        textoIdadeC.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        textoIdadeC.setForeground(new java.awt.Color(0, 0, 0));
        textoIdadeC.setText("Idade 50 á 69 :");

        textoIdadeD.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        textoIdadeD.setForeground(new java.awt.Color(0, 0, 0));
        textoIdadeD.setText("Idade Menor 50 :");

        textoResA.setBackground(new java.awt.Color(0, 153, 0));
        textoResA.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        textoResA.setForeground(new java.awt.Color(0, 153, 0));

        textoResB.setBackground(new java.awt.Color(0, 153, 0));
        textoResB.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        textoResB.setForeground(new java.awt.Color(0, 153, 0));

        textoResC.setBackground(new java.awt.Color(0, 153, 0));
        textoResC.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        textoResC.setForeground(new java.awt.Color(0, 153, 0));

        textoResD.setBackground(new java.awt.Color(0, 153, 0));
        textoResD.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        textoResD.setForeground(new java.awt.Color(0, 153, 0));

        botaoCalcular.setBackground(new java.awt.Color(85, 78, 164));
        botaoCalcular.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botaoCalcular.setForeground(new java.awt.Color(255, 255, 255));
        botaoCalcular.setText("Calcular média de vacinação");
        botaoCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCalcularActionPerformed(evt);
            }
        });

        botaoSair.setBackground(new java.awt.Color(255, 0, 0));
        botaoSair.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botaoSair.setForeground(new java.awt.Color(255, 255, 255));
        botaoSair.setText("SAIR");
        botaoSair.setBorder(null);
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        campoDataInicial.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(314, 314, 314)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(123, 123, 123)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(textoData)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(13, 13, 13))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(textoIdadeB)
                                        .addGap(18, 18, 18)
                                        .addComponent(textoResB))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(textoDestaque)
                                            .addGap(138, 138, 138)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(textoIdadeA)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textoResA)))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(81, 81, 81)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(textoIdadeC)
                                        .addGap(18, 18, 18)
                                        .addComponent(textoResC))
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(textoIdadeD)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textoResD))
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(473, 473, 473)
                        .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(340, Short.MAX_VALUE)
                .addComponent(botaoCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(474, 474, 474))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel2)
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoData)
                    .addComponent(campoDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoDestaque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoIdadeA)
                    .addComponent(textoResA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoIdadeB)
                    .addComponent(textoResB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoIdadeC)
                    .addComponent(textoResC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoIdadeD)
                    .addComponent(textoResD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCalcularActionPerformed
        
        SimpleDateFormat formatData = new SimpleDateFormat("dd-MM-yyyy");
        
        if(campoDataInicial.getDate() == null && campoDataFinal.getDate() == null)
        {
            JOptionPane.showMessageDialog(null,"Campos de data em branco" ,"Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //pega datas usando componente jcallendar (baixar a parte)
        String dataInicial =formatData.format(campoDataInicial.getDate());
        String dataFinal =formatData.format(campoDataFinal.getDate());
        
        //retorna array de doubles
        //variaveis de idade correspondem com a ordem  I II III IV do pdf de descriçao do projeto
        double[] medias = GerenciadorDeData.gerarRelatorio(dataInicial, dataFinal);
        
        if(medias != null)
        {
            textoResA.setText("" + medias[0]);
            textoResB.setText("" +  medias[1]);
            textoResC.setText("" +  medias[2]);
            textoResD.setText("" +  medias[3]);
        }else
        {
           JOptionPane.showMessageDialog(null,"Erro de data, data inicial menor que final ?" ,"Erro", JOptionPane.ERROR_MESSAGE); 
        }
        
        //textoIdadeA.setText(tempStr);
    }//GEN-LAST:event_botaoCalcularActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCalcular;
    private javax.swing.JButton botaoSair;
    private com.toedter.calendar.JDateChooser campoDataFinal;
    private com.toedter.calendar.JDateChooser campoDataInicial;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel textoData;
    private javax.swing.JLabel textoDestaque;
    private javax.swing.JLabel textoIdadeA;
    private javax.swing.JLabel textoIdadeB;
    private javax.swing.JLabel textoIdadeC;
    private javax.swing.JLabel textoIdadeD;
    private javax.swing.JLabel textoResA;
    private javax.swing.JLabel textoResB;
    private javax.swing.JLabel textoResC;
    private javax.swing.JLabel textoResD;
    // End of variables declaration//GEN-END:variables

    private void mudarLingCalen() {
        campoDataInicial.setLocale(new Locale("pt", "BR"));
        campoDataFinal.setLocale(new Locale("pt", "BR"));
    }
}
